### PR TITLE
added philippine regions

### PR DESCRIPTION
**Pull request by maning**
This is in relation to https://github.com/osmandapp/OsmAnd-misc/issues/86, I splitted the philippines into 3 major island groups (luzon, visayas, mindanao).  The initial poly was based on geofabrik's. philippine.poly.  The splits are only along the sea, so, other than probably route=ferrys, no critical routing data maybe affected by the split.  I also added an entry in the indexes.xml at https://github.com/osmandapp/OsmAnd-tools/pull/103.  I have not commented out the original philippine entry since some users (with very good bandwidth) might prefer to download the whole country. 

Thanks in advance for considering the two PRs.

### CODE REVIEW

**Comment by xmd5a2** [comment]
Philippines are only 112Mb to download. Is it really necessary to split it?

**Comment by vshcherb** [comment]
We can keep that pull-request for history, for now < 200 MB is not split for performance reasons of the server.

**Comment by maning** [comment]
Last week it was 171 MB already which is very difficult to download for areas with very slow connection especially in remote areas and even in major cities in Mindanao and Visayas. Thank you for considering this request.  I will reactivate this again once we reach the > 200 MB cap.

**Comment by vshcherb** [comment]
Can you please specify for which purpose: download or update? Let us think a bit about areas with bad internet connection, that might be an important point

**Comment by maning** [comment]
Is there a difference between download or update?  For a brief context, we run several osm workshops in many remote areas in the PH (mostly in the Visayas and Mindanao).  The mobile app we use is OsmAnd both for general purpose navigation and more importantly, for field data collection because of the offline features. Downloading anything more than 100 MB is really difficult in these areas even with using expensive "unlimited" plans. We tried downloading prior to the workshop and then share the obf file via bluetooth, but this requires a few more steps and does not solve the big download issue when the participants update the map on their own. Thanks!

**Comment by gitGOwin** [comment]
Thanks @maning. I should add that option will let more low-end or older devices use regional instead of the national map instead.

**Comment by vshcherb** [comment]
Now there is no difference, but we plan to add incremental updates feature.

**Comment by maning** [comment]
@vshcherb, incremental updates is better, but for now, please consider the proposed split to 3 island regions. tnx!

**Pull request closed without merging**
