### PR TITLE
Added India regions poly files

### PR DESCRIPTION
**Pull request by yogiks**
I've added India state region poly files to osm-planet/polygons/asia-india with a poly file of the same name in osm-planet/polygons/. Please review.

Thanks.:)

### CODE REVIEW

**Comment by yogiks** [comment]
Hi,

India is a big country and OSM community here is gradually expanding with more people contributing to OSM. Given the Internet connectivity issue here, this would help a lot for the local users to get region maps. I've split the country as per administrative boundaries here http://simple.wikipedia.org/wiki/India#Indian_states

**Comment by yogiks** [comment]
I've corrected two poly files which had multiple polygons and pushed to my repo. Can I re-open the above pull-request here or should I create a new one.?

Thanks,
yogi

**Comment by yogiks** [comment]
Commit changes here --
https://github.com/yogiks/OsmAnd-misc/commit/3046976fbd0749fd3843effb007456c42a1ef4ab

**Comment by xmd5a2** [comment]
Added manually

**Comment by yogiks** [comment]
Thanks xmd5a2.. :)

Could you or any of the developers kindly look into this commit to OsmAnd-tools repo -- https://github.com/yogiks/OsmAnd-tools/commit/fe6935f1a8b8c1ccc7170f87645382df7790940f

Please suggest if there are any corrections.

**Comment by vshcherb** [comment]
We are still not sure about processing India states, today we don't have good UI to have tons of maps and India is not the biggest our concern, there are countries bigger by size China and bigger by OSM data Japan, which are not split yet. Anyway every change will require UI update.

**Comment by yogiks** [comment]
Thanks for the response. I understand the UI problem, having too many maps to download would not look good. But I hope it'll be atleast useful for the people who need them and given the Internet connectivity situation in India, regional maps are much needed for the Osmand users here. I guess that may not be the situation in those two countries. There's no hurry, but please consider this and kindly process when we get the UI update. 

Should I need to create a pull request again during UI update or the same one now will do.?

**Comment by vshcherb** [comment]
Hi,

Let me just try to explain the situation. This functionality is not really part of the product. Of course without UI update it is not good to do. First of all we would like to know exact reason why we should provide split versions. Second, we are making decision to process on our servers or not, using the stats, bandwidth, CPU power and so on. We know how to include and implement that functionality, we just don't see enough value yet. 
In a fact, I know examples that people would like to get daily updates for small areas, but it is not doable on our servers for the whole world. Of course it is doable for 1 country, but we don't want discriminate other countries, because we have users around the world. 
So usually we start thinking of split, when obf.zip reaches 500MB, even then it is still the question of value and so on. Netherlands reached 1 GB , but we are still not sure do we want to split or not. Splitting provides other problems that people don't know the region and so on.

So please explain the immediate value or the goal you would like to get and we will consider it. But if you want to have small daily updates, today this is the question to the specific community.

P.S. please explain internet situation in India as well.

**Comment by yogiks** [comment]
Thank you for the explanation. Providing split versions will help the users to get offline maps at lower size and since regions are divided as per administrative regions, users will download only those region maps which are needed instead of getting whole India(>200MB).

As I can see now, except Italy(and now Japan), most of the other countries regions are provided by Geofabrik. And if India is also split, it will benefit users here and may increase the OsmAnd userbase which will in turn benefit whole OSM community in India. As you say, splitting provides other problems that people don't know the region, we can keep both - whole India(processed by Geofabrik) and its admin regions(processed at OsmAnd servers) like its the case with Italy now.

India is a developing country where access to quality maps is as problematic as access to good quality Internet. Google maps is no where useful in Indian countryside where there's not even cellular connectivity. This is where OsmAnd fills the gaps for us providing offline maps with navigation for greater part of the nation and OSM community in India is also increasing at steady state. In metro cities(there are 6 of them in whole country) and state capitals(24 cities), we get high speed mobile Internet with 100-200KBps in 3G connectivity. In all the other parts of India, with 2G connection, its less than 10-15KBps. This translates to 4-5hrs to get offline map of whole India(>200MB). But if the regions are split as per administrative states, I hope they will be less than 10-20MB per region and will help more number of OsmAnd users.

Please consider this split and we don't need daily updates anyway, since weekly or bi-weekly updates will suffice as what we are getting now.

**Pull request merged**
