### PR TITLE
Simplify upper-bavaria.poly

### PR DESCRIPTION
**Pull request by OsmMUC**
The polygon file for Upper Bavaria in Germany contains a small subtracted area (less than 1.2 km by 0.36 km, circumference 2.54km). The proposal is to remove this subtraction from the polygon file so that the handful of objects contained in this area are included in the OBF file for Upper Bavaria. Else, the user might not realize that objects are missing on the map if the Upper Bavaria offline map is activated, but the Swabia offline map is not, as many other objects are shown in that area because they partially lie outside the subtracted area.
Attached a screen shot from JOSM with extent of the area indicated (also see scale in upper left corner).
Attached also screen shots to highlight objects (benches, pier) subtly missing if Upper Bavarial offline map is activated, but Swabia map is not (this is zoomed in to a small subarea to highlight the subtle differences, it is not showing the overall polygon subtraction area).

Screenshot_20230208_141137_OsmAnd+
Screenshot_20230208_141113_OsmAnd+

### CODE REVIEW

**Comment by OsmMUC** [comment]
Here is another screenshot from JOSM, this time showing the objects in the area to give some context/perspective. Highlighted in red the area that is currently being subtracted from the Upper Bavaria area.
To give an indication of the location of the area: One of the benches is located at 47.7174308, 10.8143294 (node 4350252915).

**Comment by vshcherb** [comment]
The boundaries are always cause we want a bit extra but not too much to not break address search

**Comment by OsmMUC** [comment]
I fully understand the reasons for having the polygon area a bit larger than the region targeted by an OBF, and agree. Just saying that in this case (and others), the purely geometrical extension of the "core" area that should be covered by the OBF creates a really small subtraction (area not included). 
With regard to address search, I am actually proposing to very slightly increase the extension (by removing the subtraction), so that shouldn't affect the address search at all.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14194mqta, Released: 2023-02-22
22.02.23 master
`47.717336, 10.812571`


<details><summary>Upper Bavaria Live</summary>
Screenshot 2023-01-31 at 11 19 41
Screenshot 2023-01-31 at 11 19 41
</details> 

<details><summary>Swabia</summary>
Screenshot 2023-01-31 at 11 19 41
Screenshot 2023-01-31 at 11 19 41
</details>

**Comment by OsmMUC** [comment]
Thanks, @Zirochkabila! That is similar to what I am seeing, too. As expected and intended, looking good.
While the live updates show changed objects since the creation of the underlying full OBF only, I'd expect to see the full and proper picture once the March update of the full regional OBF for Upper Bavaria becomes available. Then, also the pier would become visible with only the Upper Bavaria region enabled, and the Swabia region off.

**Pull request merged**
